# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - stepwise

on:
  push:
    branches:
      - dev
  workflow_dispatch:

concurrency:
  group: stepwise-dev-deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: |
          npm ci --prefer-offline --no-audit

      - name: Build app
        run: npm run build --if-present

      - name: Prune dev dependencies
        run: npm prune --omit=dev

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0005B6639AFA42A99B5C8166397CDC0E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_ACC8A25210E44791AC4CED6005022DCF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_45E02192D34446D2B91597CB6967F18E }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'stepwise'
          slot-name: 'Production'
          package: .
          
