name: Build and deploy frontend to Azure Web App - stepwise

on:
  push:
    branches: [google-auth]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"

      - run: npm ci
      - run: npm run build

      - uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: web-dist
          path: dist

      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5DCCFAC7E4954A09889F914199D9F584 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_606CB5FAD3B84B73A529C93FAC8D83DA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_69D1F1930BCB496797DB8A1DF10B705D }}

      - uses: azure/webapps-deploy@v3
        with:
          app-name: stepwise
          package: dist
